"""add location race_position and lap tables

Revision ID: 679e7323b79c
Revises: 5f8ae59ccc8a
Create Date: 2026-06-23 20:10:43.642356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '679e7323b79c'
down_revision: Union[str, Sequence[str], None] = '5f8ae59ccc8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_key', sa.Integer(), nullable=False),
    sa.Column('driver_number', sa.Integer(), nullable=False),
    sa.Column('lap_number', sa.Integer(), nullable=True),
    sa.Column('date_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lap_duration', sa.Float(), nullable=True),
    sa.Column('duration_sector_1', sa.Float(), nullable=True),
    sa.Column('duration_sector_2', sa.Float(), nullable=True),
    sa.Column('duration_sector_3', sa.Float(), nullable=True),
    sa.Column('i1_speed', sa.Integer(), nullable=True),
    sa.Column('i2_speed', sa.Integer(), nullable=True),
    sa.Column('is_pit_out_lap', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['session_key'], ['sessions.session_key'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_laps_driver_number'), 'laps', ['driver_number'], unique=False)
    op.create_index(op.f('ix_laps_session_key'), 'laps', ['session_key'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_key', sa.Integer(), nullable=False),
    sa.Column('driver_number', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('z', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['session_key'], ['sessions.session_key'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_date'), 'locations', ['date'], unique=False)
    op.create_index(op.f('ix_locations_driver_number'), 'locations', ['driver_number'], unique=False)
    op.create_index(op.f('ix_locations_session_key'), 'locations', ['session_key'], unique=False)
    op.create_table('race_positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_key', sa.Integer(), nullable=False),
    sa.Column('driver_number', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_key'], ['sessions.session_key'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_race_positions_date'), 'race_positions', ['date'], unique=False)
    op.create_index(op.f('ix_race_positions_driver_number'), 'race_positions', ['driver_number'], unique=False)
    op.create_index(op.f('ix_race_positions_session_key'), 'race_positions', ['session_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_race_positions_session_key'), table_name='race_positions')
    op.drop_index(op.f('ix_race_positions_driver_number'), table_name='race_positions')
    op.drop_index(op.f('ix_race_positions_date'), table_name='race_positions')
    op.drop_table('race_positions')
    op.drop_index(op.f('ix_locations_session_key'), table_name='locations')
    op.drop_index(op.f('ix_locations_driver_number'), table_name='locations')
    op.drop_index(op.f('ix_locations_date'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_laps_session_key'), table_name='laps')
    op.drop_index(op.f('ix_laps_driver_number'), table_name='laps')
    op.drop_table('laps')
    # ### end Alembic commands ###
