"""initial schema

Revision ID: c2df5d3f5cfb
Revises: 
Create Date: 2026-06-22 19:13:33.414961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2df5d3f5cfb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circuits',
    sa.Column('circuit_key', sa.Integer(), nullable=False),
    sa.Column('circuit_short_name', sa.String(length=100), nullable=True),
    sa.Column('country_name', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('circuit_key')
    )
    op.create_table('sessions',
    sa.Column('session_key', sa.Integer(), nullable=False),
    sa.Column('session_type', sa.String(length=50), nullable=True),
    sa.Column('session_name', sa.String(length=100), nullable=True),
    sa.Column('date_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('circuit_key', sa.Integer(), nullable=True),
    sa.Column('circuit_short_name', sa.String(length=100), nullable=True),
    sa.Column('country_name', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('meeting_key', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['circuit_key'], ['circuits.circuit_key'], ),
    sa.PrimaryKeyConstraint('session_key')
    )
    op.create_index(op.f('ix_sessions_circuit_key'), 'sessions', ['circuit_key'], unique=False)
    op.create_index(op.f('ix_sessions_session_type'), 'sessions', ['session_type'], unique=False)
    op.create_index(op.f('ix_sessions_year'), 'sessions', ['year'], unique=False)
    op.create_table('drivers',
    sa.Column('session_key', sa.Integer(), nullable=False),
    sa.Column('driver_number', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('team_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['session_key'], ['sessions.session_key'], ),
    sa.PrimaryKeyConstraint('session_key', 'driver_number')
    )
    op.create_table('session_results',
    sa.Column('session_key', sa.Integer(), nullable=False),
    sa.Column('driver_number', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('number_of_laps', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('gap_to_leader', sa.Float(), nullable=True),
    sa.Column('gap_to_leader_raw', sa.String(length=50), nullable=True),
    sa.Column('dnf', sa.Boolean(), nullable=True),
    sa.Column('dns', sa.Boolean(), nullable=True),
    sa.Column('dsq', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['session_key'], ['sessions.session_key'], ),
    sa.PrimaryKeyConstraint('session_key', 'driver_number')
    )
    op.create_index(op.f('ix_session_results_position'), 'session_results', ['position'], unique=False)
    op.create_table('weather',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_key', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('air_temperature', sa.Float(), nullable=True),
    sa.Column('track_temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.Integer(), nullable=True),
    sa.Column('rainfall', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['session_key'], ['sessions.session_key'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_session_key'), 'weather', ['session_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_session_key'), table_name='weather')
    op.drop_table('weather')
    op.drop_index(op.f('ix_session_results_position'), table_name='session_results')
    op.drop_table('session_results')
    op.drop_table('drivers')
    op.drop_index(op.f('ix_sessions_year'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_session_type'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_circuit_key'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('circuits')
    # ### end Alembic commands ###
