name: Docker Images CI Pipeline

on:
  push:
    branches: [trunk]
    paths:
      # Include
      - "backend/**"
      - "frontend/**"
      - ".github/workflows/ci-pipeline.yaml"

      # Exclude
      - "!**.md"

  workflow_dispatch:

jobs:
  call-docker-build:
    permissions:
      contents: read
      packages: write

    uses: Phylip28/gha-workflows/.github/workflows/docker-ghcr.yaml@trunk
    with:
      services: '["backend", "frontend"]'
    secrets: inherit
